name: Automatizar PR con MLOPS

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Verificar mensaje de commit
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Mensaje del commit: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" != *"MLOPS"* ]]; then
            echo "El commit no contiene la palabra MLOPS. Se omite el PR."
            exit 78
          fi

      - name: Crear Pull Request automático
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR for MLOPS"
          title: "PR Automático generado por MLOPS"
          body: "Este Pull Request se creó automáticamente porque el último commit incluyó la palabra clave MLOPS."
          branch: ${{ github.ref_name }}
          base: main
